Practica Mobile WIP
Code4PuertoRico/paravotar pull request #101
Opened 2020-05-02 19:37 UTC by Jpadilla1

2020-05-26 12:42 UTC, eluciano11 requested changes
LGTM, encontre unos boberías que se podrían arreglar.

2020-05-26 12:42 UTC, eluciano11 commented on src/hooks/useMachineWithComponent.tsx
> +      whiteSpace: "pre-line",
No deberíamos usar Tailwind aquí en lugar de inline styles?

2020-05-26 12:42 UTC, eluciano11 commented on src/hooks/useMachineWithComponent.tsx
> +  const Component = meta && meta.Component ? meta.Component : defaultComponent
Nit: Use optional chaining? `meta?.Component || defaultComponent` (?)

2020-05-26 12:42 UTC, eluciano11 commented on src/packages/practica/components/Flow.tsx
> +import _ from "lodash"
Por lo que veo, no estas usando lodash. Please remove.

2020-05-26 12:42 UTC, eluciano11 commented on src/packages/practica/components/SelectingBallot.tsx
> +import _ from "lodash"
Question, pq no estas usando los imports directos a las funciones que vas a usar?

2020-05-26 12:42 UTC, eluciano11 commented on src/packages/practica/components/SelectingVotingMethod.tsx
> +  current,
Not being used.

2020-05-26 12:42 UTC, eluciano11 commented on src/packages/practica/services/BallotService.ts
> +import _ from "lodash"
Not being used.

2020-05-26 12:42 UTC, eluciano11 commented on src/packages/practica/services/BallotService.ts
> +    [key: string]: { r: number; c: number }[]
Qué significa r y c?

2020-05-31 20:00 UTC, Jpadilla1 commented on src/packages/practica/components/SelectingBallot.tsx
> +import _ from "lodash"
Por conveniencia really. Instale y configure gatsby-plugin-lodash para tener tree shaking y no afectar el bundle size.

2020-05-31 20:01 UTC, Jpadilla1 commented on src/packages/practica/services/BallotService.ts
> +    [key: string]: { r: number; c: number }[]
r y c significa rows y columns, deja escribirlo completo para que sea mas claro

2020-05-31 20:22 UTC, eluciano11 approved these changes
🚀

2020-05-31 20:25 UTC, merged