Add the ability to remind users to register to vote via iCalendar events
Code4PuertoRico/paravotar pull request #136
Opened 2020-08-07 05:19 UTC by krismuniz

## Description

Añade la capacidad de añadir tres recordatorios para inscribirse en una Junta de Inscripción Permanente.

Crea dos archivos tipo `.ics` (uno en inglés y el otro en español). Cada file enumera tres iCalendar events:

- 1 de septiembre de 2020: Faltan dos semanas! [...]
- 7 de septiembre de 2020: Falta una semana! [...]
- 14 de septiembre de 2020: Hoy es el último día para [...]

(parafraseado)

## Additional Context

https://github.com/Code4PuertoRico/paravotar/issues/44#issuecomment-669649108 Este PR probablemente esté bloqueado hasta que nos pongamos de acuerdo en cuanto al "copy" que debemos usar para el site y para los eventos del calendario. 

Closes #44

## Next Steps

Probablemente sea necesario generalizar la manera en que se generan los iCalendar files para otros recordatorios a lo largo de la vida del proyecto. Por ejemplo: añadir un recordatorio para la fecha de las primarias y/o elecciones generales. Incluso darle al usuario la habilidad de escoger cuál es su junta de inscripción permanente y añadir la dirección a la invitación.

Hay Gatsby plugins que podrían ayudar con esto. También ver esta discusión: https://github.com/Code4PuertoRico/paravotar/issues/44#issuecomment-669646093

## Screenshots

### Desktop

<img width="1286" alt="Screen Shot 2020-08-06 at 10 07 33 PM" src="https://user-images.githubusercontent.com/860507/89611254-8e436500-d831-11ea-9940-88ea3cd18dca.png">
<img width="1286" alt="Screen Shot 2020-08-06 at 10 07 26 PM" src="https://user-images.githubusercontent.com/860507/89611258-91d6ec00-d831-11ea-9c60-3b9cacf7d957.png">

### Mobile (iOS)

![IMG_2644](https://user-images.githubusercontent.com/860507/89611300-b03ce780-d831-11ea-97e3-0093cd7c09c4.PNG)

### Gracias!

2020-08-07 17:39 UTC, froi commented
Seem to be a dependency issues. @eluciano11 @Jpadilla1 

```
warning Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`
  
   ⚠️  Tailwind is not purging unused styles because no template paths have been provided.
      If you have manually configured PurgeCSS outside of Tailwind or are deliberately not
      removing unused styles, set `purge: false` in your Tailwind config file to silence
      this warning.
   
      https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
  
   ⚠️  Tailwind is not purging unused styles because no template paths have been provided.
      If you have manually configured PurgeCSS outside of Tailwind or are deliberately not
      removing unused styles, set `purge: false` in your Tailwind config file to silence
      this warning.
   
      https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
failed Building production JavaScript and CSS bundles - 47.331s
error Generating JavaScript bundles failed
```

2020-08-08 01:42 UTC, krismuniz commented
Local error output from `yarn build` is the following:

```
failed Building production JavaScript and CSS bundles - 35.623s

ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Bundle Analyzer - Token not found, please specify a token using BUNDLE_ANALYZER_TOKEN env variable

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

2020-08-08 15:07 UTC, eluciano11 requested changes

2020-08-08 15:07 UTC, eluciano11 commented on src/locales/es/translations.json
> +    "enrollment-reminder-guide2": "Añade tres eventos a tu calendario para recordarte hacer la gestión de sacar tu tarjeta electoral antes de la fecha límite para inscribirse. No lo dejes para lo últ
```suggestion
    "enrollment-reminder-guide2": "Añade tres eventos a tu calendario para recordarte hacer la gestión de sacar tu tarjeta electoral antes de la fecha límite para inscribirse. No lo dejes para lo último. Te damos 3 chances para que lo logres. ¡Vamos a ti!",
```

2020-08-08 15:08 UTC, eluciano11 commented
@froi eso del warning que mencionas lo tenemos que arreglar pero creo que el issue que estamos viendo es por lo que menciona @krismuniz.

@krismuniz awesome work, todo se ve super bien! tengo un minor feedback que debemos mirar antes de merge:

1. Debemos añadir esta sección al sidebar y al navbar de mobile. Yo le pondría como título "Crea un recordatorio" o algo así.
<img width="1594" alt="Screen_Shot_2020-08-08_at_10_57_10_AM" src="https://user-images.githubusercontent.com/6109151/89713677-563e3e00-d967-11ea-95b9-a6141a92bc15.png">

2. Cuando intenté abrir el ics en mi Mac no me funciono. No creo que esto sea un big issue pq la mayoría del trafico es de celulares pero creo que debemos verificar qué esta pasando.
![image](https://user-images.githubusercontent.com/6109151/89713552-6c97ca00-d966-11ea-8b72-c61a1e84076d.png)

2020-08-08 15:27 UTC, froi commented
> Looking at the build.yml workflow, there's a reference to BUNDLE_ANALYZER_TOKEN. It appears that since my branch is in a fork of the code4puertorico/paravotar repo, {{ secrets.BUNDLE_ANALYZER_TOKEN }} is undefined.

Hmmmm, strange. It shouldn’t matter if you’re pushing a fork. The PR, the checks, and the Action should be running in this repo’s context not yours. I’ll take a 👀.

2020-08-09 18:51 UTC, krismuniz commented
Ya hice los cambios necesarios:

- añadí el símbolo de exclamación que olvidé
- arreglé los iCalendar files (los pasé por un validation tool y no estaban up to standard AT ALL 😂)
- arreglé un incorrect id en el heading del componente `<EnrollmentReminder />`

Aprendí un par de cosas importantes de iCalendar files:

1. Lines should be hard-wrapped at 75 characters to conform to the standard
2. Empty lines are not specified so some calendar clients don't know what to do with them
3. Some characters like commas need to be escaped :)
4. You shouldn't try to be clever and edit them manually unless you have a lot of patience and know what you are doing
5. This validator is super handy: https://icalendar.org/validator.html

2020-08-10 03:05 UTC, eluciano11 commented
🚀 

Amazing work, gracias por todo el trabajo, por compartir la info de los ics y el ics validator!

💪 👏

2020-08-10 03:05 UTC, eluciano11 approved these changes

2020-08-10 03:06 UTC, merged